import React, { createContext, useContext, useEffect, useState } from 'react';
import { useAuth } from './auth-context';

interface LanguageContextValue {
  lang: 'es' | 'en';
  setLanguage: (language: 'es' | 'en') => void;
  t: (key: string) => string;
}

const translations: Record<'es' | 'en', Record<string, string>> = {
  es: {
    settings: 'Ajustes',
    profile: 'Perfil del jugador',
    age: 'Edad',
    playerName: 'Nombre del jugador',
    nickname: 'Apodo',
    status: 'Estado',
    statusPlaceholder: 'Escribe algo sobre ti...',
    language: 'Idioma',
    spanish: 'Español',
    english: 'English',
    save: 'Guardar cambios',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    saved: 'Cambios guardados',
    close: 'Cerrar',
    namePlaceholder: 'Tu nombre actual',
    nicknamePlaceholder: 'Cómo quieres que te llamen',
    agePlaceholder: 'Tu edad',
    languageHint: 'Cambia el idioma de la interfaz',
    playerNameHint: 'Este nombre se muestra a otros jugadores',
    online: 'En línea',
    connecting: 'Conectando...',
    reconnecting: 'Reconectando...',
    logout: 'Salir',
    chatPlaceholder: 'Decir...',
    myHouse: 'Mi Casa',
    rooms: 'Salas',
    inventory: 'Inventario',
    requests: 'Solicitudes',
    settingsShort: 'Ajustes',
    actionChangeCostume: 'Cambiar ropa',
    actionDance: 'Bailar',
    actionEmotions: 'Emociones',
    actionSit: 'Sentarse',
    standUp: 'Levantarse',
    actionPhoto: 'Fotografía',
    actionFarm: 'Mi Granja',
    actionSettings: 'Config.',
    back: 'Volver',
    emptyInventory: 'Inventario vacío',
    emptyInventoryHint: 'Recoge objetos en el mundo para verlos aquí',
    ranchGestures: 'GESTOS DEL RANCHO',
    travelBag: 'BOLSA DE VIAJE',
    level: 'Nivel',
    farmer: 'Granjero',
    health: 'Vida',
    gold: 'Oro',
    diamonds: 'Diamantes',
    login: 'Entrar',
    createAccount: 'Crear cuenta',
    createKicker: 'Crea tu personaje y empieza tu historia',
    waitingKicker: 'Tu ciudad campestre te está esperando',
    communityRooms: 'Salas de la comunidad',
    createNewRoom: 'Crear nueva sala',
    myRooms: 'Mis salas',
    exploreCorners: 'Explora nuevos rincones',
    communityDescription: 'Toca una sala para entrar directamente. Cada casa tiene un ID único generado por FarmCity.',
    loadingRooms: 'Cargando tus salas…',
    loadingPublicRooms: 'Buscando salas abiertas…',
    noRooms: 'Aún no tienes salas',
    noRoomsHint: 'Crea tu primera sala con el botón de arriba.',
    noPublicRooms: 'Aún no hay salas públicas',
    noPublicRoomsHint: 'Crea la primera desde “Mi Casa” y aparecerá aquí.',
    public: 'Pública',
    private: 'Privada',
    createdOn: 'Creada el',
    edit: 'Editar',
    delete: 'Eliminar',
    privateRoomsNote: 'Las salas privadas no aparecen en este listado.',
    backToPlaza: 'Volver a la plaza',
    refreshRooms: 'Actualizar salas',
  },
  en: {
    settings: 'Settings',
    profile: 'Player profile',
    age: 'Age',
    playerName: 'Player name',
    nickname: 'Nickname',
    status: 'Status',
    statusPlaceholder: 'Write something about yourself...',
    language: 'Language',
    spanish: 'Español',
    english: 'English',
    save: 'Save changes',
    saving: 'Saving...',
    cancel: 'Cancel',
    saved: 'Changes saved',
    close: 'Close',
    namePlaceholder: 'Your current name',
    nicknamePlaceholder: 'What should people call you?',
    agePlaceholder: 'Your age',
    languageHint: 'Change the interface language',
    playerNameHint: 'This name is shown to other players',
    online: 'Online',
    connecting: 'Connecting...',
    reconnecting: 'Reconnecting...',
    logout: 'Log out',
    chatPlaceholder: 'Say something...',
    myHouse: 'My House',
    rooms: 'Rooms',
    inventory: 'Inventory',
    requests: 'Requests',
    settingsShort: 'Settings',
    actionChangeCostume: 'Change outfit',
    actionDance: 'Dance',
    actionEmotions: 'Emotes',
    actionSit: 'Sit down',
    standUp: 'Stand up',
    actionPhoto: 'Take photo',
    actionFarm: 'My Farm',
    actionSettings: 'Settings',
    back: 'Back',
    emptyInventory: 'Inventory is empty',
    emptyInventoryHint: 'Collect objects in the world to see them here',
    ranchGestures: 'RANCH GESTURES',
    travelBag: 'TRAVEL BAG',
    level: 'Level',
    farmer: 'Farmer',
    health: 'Health',
    gold: 'Gold',
    diamonds: 'Diamonds',
    login: 'Log in',
    createAccount: 'Create account',
    createKicker: 'Create your character and start your story',
    waitingKicker: 'Your countryside city is waiting for you',
    communityRooms: 'Community rooms',
    createNewRoom: 'Create new room',
    myRooms: 'My rooms',
    exploreCorners: 'Explore new corners',
    communityDescription: 'Tap a room to enter directly. Every home has a unique ID generated by FarmCity.',
    loadingRooms: 'Loading your rooms…',
    loadingPublicRooms: 'Looking for open rooms…',
    noRooms: 'You do not have rooms yet',
    noRoomsHint: 'Create your first room with the button above.',
    noPublicRooms: 'There are no public rooms yet',
    noPublicRoomsHint: 'Create the first one from “My House” and it will appear here.',
    public: 'Public',
    private: 'Private',
    createdOn: 'Created on',
    edit: 'Edit',
    delete: 'Delete',
    privateRoomsNote: 'Private rooms do not appear in this list.',
    backToPlaza: 'Back to plaza',
    refreshRooms: 'Refresh rooms',
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'es',
  setLanguage: () => undefined,
  t: (key) => translations.es[key] ?? key,
});

const LANGUAGE_KEY = 'farmcity_language';

function readStoredLanguage(): 'es' | 'en' {
  try {
    return localStorage.getItem(LANGUAGE_KEY) === 'en' ? 'en' : 'es';
  } catch {
    return 'es';
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { player } = useAuth();
  const [lang, setLang] = useState<'es' | 'en'>(() => readStoredLanguage());

  useEffect(() => {
    if (player?.language) setLang(player.language);
  }, [player?.language]);

  const setLanguage = (language: 'es' | 'en') => {
    setLang(language);
    try {
      localStorage.setItem(LANGUAGE_KEY, language);
    } catch {
      // The language remains active for this session.
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t: (key) => translations[lang][key] ?? key }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
